name: swift_synoptic
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - antlr-python-runtime=4.7.2
  - appdirs=1.4.4
  - blosc=1.21.0
  - bokeh=2.3.0
  - brotli=1.0.9
  - brotlipy=0.7.0
  - brunsli=0.1
  - bzip2=1.0.8
  - c-ares=1.17.1
  - ca-certificates=2020.12.5
  - cartopy=0.18.0
  - certifi=2020.12.5
  - cf-units=2.1.4
  - cffi=1.14.5
  - cftime=1.2.1
  - chardet=4.0.0
  - charls=2.2.0
  - click=7.1.2
  - cloudpickle=1.6.0
  - cryptography=3.4.6
  - curl=7.75.0
  - cycler=0.10.0
  - cytoolz=0.11.0
  - dask=2021.3.0
  - dask-core=2021.3.0
  - decorator=4.4.2
  - distributed=2021.3.0
  - expat=2.2.10
  - freetype=2.10.4
  - fsspec=0.8.7
  - geos=3.9.1
  - giflib=5.2.1
  - hdf4=4.2.13
  - hdf5=1.10.6
  - heapdict=1.0.1
  - idna=2.10
  - imagecodecs=2021.1.28
  - imageio=2.9.0
  - iris=3.0.1
  - jinja2=2.11.3
  - jpeg=9d
  - jxrlib=1.1
  - kiwisolver=1.3.1
  - krb5=1.17.2
  - lcms2=2.12
  - ld_impl_linux-64=2.35.1
  - lerc=2.2.1
  - libaec=1.0.4
  - libblas=3.9.0
  - libcblas=3.9.0
  - libcurl=7.75.0
  - libdeflate=1.7
  - libedit=3.1.20191231
  - libev=4.33
  - libffi=3.3
  - libgcc-ng=9.3.0
  - libgfortran-ng=9.3.0
  - libgfortran5=9.3.0
  - libgomp=9.3.0
  - liblapack=3.9.0
  - libnetcdf=4.7.4
  - libnghttp2=1.43.0
  - libopenblas=0.3.12
  - libpng=1.6.37
  - libssh2=1.9.0
  - libstdcxx-ng=9.3.0
  - libtiff=4.2.0
  - libwebp-base=1.2.0
  - libzopfli=1.0.3
  - locket=0.2.0
  - lz4-c=1.9.3
  - markupsafe=1.1.1
  - matplotlib-base=3.3.4
  - msgpack-python=1.0.2
  - ncurses=6.2
  - netcdf4=1.5.6
  - networkx=2.5
  - numpy=1.20.1
  - olefile=0.46
  - openjpeg=2.4.0
  - openssl=1.1.1k
  - packaging=20.9
  - pandas=1.2.3
  - partd=1.1.0
  - pillow=8.1.2
  - pip=21.0.1
  - pooch=1.3.0
  - proj=7.2.0
  - psutil=5.8.0
  - pycparser=2.20
  - pyke=1.1.1
  - pyopenssl=20.0.1
  - pyparsing=2.4.7
  - pyshp=2.1.3
  - pysocks=1.7.1
  - pyspharm=1.0.9
  - python=3.8.8
  - python-dateutil=2.8.1
  - python-xxhash=2.0.0
  - python_abi=3.8
  - pytz=2021.1
  - pywavelets=1.1.1
  - pyyaml=5.4.1
  - readline=8.0
  - requests=2.25.1
  - scikit-image=0.18.1
  - scipy=1.6.1
  - setuptools=49.6.0
  - shapely=1.7.1
  - six=1.15.0
  - snappy=1.1.8
  - sortedcontainers=2.3.0
  - sqlite=3.35.2
  - tblib=1.7.0
  - tifffile=2021.3.17
  - tk=8.6.10
  - toolz=0.11.1
  - tornado=6.1
  - typing_extensions=3.7.4.3
  - tzdata=2021a
  - udunits2=2.2.27.27
  - urllib3=1.26.4
  - wheel=0.36.2
  - windspharm=1.7.0
  - wrapt=1.12.1
  - wrf-python=1.3.2.5
  - xarray=0.17.0
  - xxhash=0.8.0
  - xz=5.2.5
  - yaml=0.2.5
  - zfp=0.5.5
  - zict=2.0.0
  - zlib=1.2.11
  - zstd=1.4.9
